from modules.core import closeness


class Course:
    def __init__(self, abbrev: str, name: str):
        self.name = name
        self.abbrev = abbrev

    @property
    def full_display(self):
        return f"[{self.abbrev}] {self.name}"

    def closeness(self, user_input: str):
        term = user_input.lower()
        return closeness(term, self.abbrev.lower()) * 2 + closeness(term, self.name.lower())


courses = {
    "Mario Bros. Circuit": Course("MBC", "Mario Bros. Circuit"),
    "Crown City": Course("CC", "Crown City"),
    "Whistlestop Summit": Course("WS", "Whistlestop Summit"),
    "DK Spaceport": Course("DKS", "DK Spaceport"),
    "Desert Hills": Course("rDH", "Desert Hills"),
    "Shy Guy Bazaar": Course("rSGB", "Shy Guy Bazaar"),
    "Wario Stadium": Course("rWS", "Wario Stadium"),
    "Airship Fortress": Course("rAF", "Airship Fortress"),
    "DK Pass": Course("rDKP", "DK Pass"),
    "Starview Peak": Course("SP", "Starview Peak"),
    "Sky-High Sundae": Course("rSHS", "Sky-High Sundae"),
    "Wario Shipyard": Course("rWSh", "Wario Shipyard"),
    "Koopa Troopa Beach": Course("rKTB", "Koopa Troopa Beach"),
    "Faraway Oasis": Course("FO", "Faraway Oasis"),
    "Peach Stadium": Course("PS", "Peach Stadium"),
    "Peach Beach": Course("rPB", "Peach Beach"),
    "Salty Salty Speedway": Course("SSS", "Salty Salty Speedway"),
    "Dino Dino Jungle": Course("rDDJ", "Dino Dino Jungle"),
    "Great ? Block Ruins": Course("GBR", "Great ? Block Ruins"),
    "Cheep Cheep Falls": Course("CCF", "Cheep Cheep Falls"),
    "Dandelion Depths": Course("DD", "Dandelion Depths"),
    "Boo Cinema": Course("BCi", "Boo Cinema"),
    "Dry Bones Burnout": Course("DBB", "Dry Bones Burnout"),
    "Moo Moo Meadows": Course("rMMM", "Moo Moo Meadows"),
    "Choco Mountain": Course("rCM", "Choco Mountain"),
    "Toad's Factory": Course("rTF", "Toad's Factory"),
    "Bowser's Castle": Course("BC", "Bowser's Castle"),
    "Acorn Heights": Course("AH", "Acorn Heights"),
    "Mario Circuit": Course("rMC", "Mario Circuit"),
    "Rainbow Road": Course("RR", "Rainbow Road")
}


class Route:
    def __init__(self, start: str, finish: str):
        self.start = start
        self.finish = finish

    @property
    def display(self):
        return f"{self.start} → {self.finish}"


routes = [
    Route("Crown City", "Mario Bros. Circuit"),
    Route("Whistlestop Summit", "Mario Bros. Circuit"),
    Route("DK Spaceport", "Mario Bros. Circuit"),
    Route("Desert Hills", "Mario Bros. Circuit"),
    Route("Shy Guy Bazaar", "Mario Bros. Circuit"),
    Route("Wario Stadium", "Mario Bros. Circuit"),
    Route("Choco Mountain", "Mario Bros. Circuit"),
    Route("Toad's Factory", "Mario Bros. Circuit"),
    Route("Mario Bros. Circuit", "Crown City"),
    Route("Whistlestop Summit", "Crown City"),
    Route("DK Spaceport", "Crown City"),
    Route("Desert Hills", "Crown City"),
    Route("Wario Stadium", "Crown City"),
    Route("Koopa Troopa Beach", "Crown City"),
    Route("Faraway Oasis", "Crown City"),
    Route("Peach Stadium", "Crown City"),
    Route("Moo Moo Meadows", "Crown City"),
    Route("Choco Mountain", "Crown City"),
    Route("Mario Bros. Circuit", "Whistlestop Summit"),
    Route("Crown City", "Whistlestop Summit"),
    Route("DK Spaceport", "Whistlestop Summit"),
    Route("Desert Hills", "Whistlestop Summit"),
    Route("Choco Mountain", "Whistlestop Summit"),
    Route("Crown City", "DK Spaceport"),
    Route("Whistlestop Summit", "DK Spaceport"),
    Route("Koopa Troopa Beach", "DK Spaceport"),
    Route("Mario Bros. Circuit", "Desert Hills"),
    Route("Crown City", "Desert Hills"),
    Route("Whistlestop Summit", "Desert Hills"),
    Route("DK Spaceport", "Desert Hills"),
    Route("Shy Guy Bazaar", "Desert Hills"),
    Route("Mario Bros. Circuit", "Shy Guy Bazaar"),
    Route("Desert Hills", "Shy Guy Bazaar"),
    Route("Wario Stadium", "Shy Guy Bazaar"),
    Route("Airship Fortress", "Shy Guy Bazaar"),
    Route("Choco Mountain", "Shy Guy Bazaar"),
    Route("Mario Bros. Circuit", "Wario Stadium"),
    Route("Crown City", "Wario Stadium"),
    Route("Shy Guy Bazaar", "Wario Stadium"),
    Route("Airship Fortress", "Wario Stadium"),
    Route("Dry Bones Burnout", "Wario Stadium"),
    Route("Choco Mountain", "Wario Stadium"),
    Route("Toad's Factory", "Wario Stadium"),
    Route("Bowser's Castle", "Wario Stadium"),
    Route("Shy Guy Bazaar", "Airship Fortress"),
    Route("Wario Stadium", "Airship Fortress"),
    Route("Dry Bones Burnout", "Airship Fortress"),
    Route("Toad's Factory", "Airship Fortress"),
    Route("Bowser's Castle", "Airship Fortress"),
    Route("Starview Peak", "DK Pass"),
    Route("Sky-High Sundae", "DK Pass"),
    Route("Wario Shipyard", "DK Pass"),
    Route("Salty Salty Speedway", "DK Pass"),
    Route("Cheep Cheep Falls", "DK Pass"),
    Route("Dandelion Depths", "DK Pass"),
    Route("Moo Moo Meadows", "DK Pass"),
    Route("DK Pass", "Starview Peak"),
    Route("Sky-High Sundae", "Starview Peak"),
    Route("Wario Shipyard", "Starview Peak"),
    Route("Cheep Cheep Falls", "Starview Peak"),
    Route("Dandelion Depths", "Starview Peak"),
    Route("Boo Cinema", "Starview Peak"),
    Route("Mario Circuit", "Starview Peak"),
    Route("DK Pass", "Sky-High Sundae"),
    Route("Starview Peak", "Sky-High Sundae"),
    Route("Wario Shipyard", "Sky-High Sundae"),
    Route("Dandelion Depths", "Sky-High Sundae"),
    Route("DK Pass", "Wario Shipyard"),
    Route("Starview Peak", "Wario Shipyard"),
    Route("Sky-High Sundae", "Wario Shipyard"),
    Route("Peach Beach", "Wario Shipyard"),
    Route("Salty Salty Speedway", "Wario Shipyard"),
    Route("Cheep Cheep Falls", "Wario Shipyard"),
    Route("Crown City", "Koopa Troopa Beach"),
    Route("Whistlestop Summit", "Koopa Troopa Beach"),
    Route("DK Spaceport", "Koopa Troopa Beach"),
    Route("Desert Hills", "Koopa Troopa Beach"),
    Route("Faraway Oasis", "Koopa Troopa Beach"),
    Route("Peach Stadium", "Koopa Troopa Beach"),
    Route("Dino Dino Jungle", "Koopa Troopa Beach"),
    Route("Great ? Block Ruins", "Koopa Troopa Beach"),
    Route("Crown City", "Faraway Oasis"),
    Route("Koopa Troopa Beach", "Faraway Oasis"),
    Route("Peach Stadium", "Faraway Oasis"),
    Route("Peach Beach", "Faraway Oasis"),
    Route("Salty Salty Speedway", "Faraway Oasis"),
    Route("Dino Dino Jungle", "Faraway Oasis"),
    Route("Great ? Block Ruins", "Faraway Oasis"),
    Route("Cheep Cheep Falls", "Faraway Oasis"),
    Route("Crown City", "Peach Stadium"),
    Route("DK Spaceport", "Peach Stadium"),
    Route("Koopa Troopa Beach", "Peach Stadium"),
    Route("Faraway Oasis", "Peach Stadium"),
    Route("Cheep Cheep Falls", "Peach Stadium"),
    Route("Moo Moo Meadows", "Peach Stadium"),
    Route("Choco Mountain", "Peach Stadium"),
    Route("Toad's Factory", "Peach Stadium"),
    Route("Mario Circuit", "Peach Stadium"),
    Route("Wario Shipyard", "Peach Beach"),
    Route("Faraway Oasis", "Peach Beach"),
    Route("Salty Salty Speedway", "Peach Beach"),
    Route("Dino Dino Jungle", "Peach Beach"),
    Route("Great ? Block Ruins", "Peach Beach"),
    Route("DK Pass", "Salty Salty Speedway"),
    Route("Sky-High Sundae", "Salty Salty Speedway"),
    Route("Wario Shipyard", "Salty Salty Speedway"),
    Route("Faraway Oasis", "Salty Salty Speedway"),
    Route("Peach Beach", "Salty Salty Speedway"),
    Route("Dino Dino Jungle", "Salty Salty Speedway"),
    Route("Great ? Block Ruins", "Salty Salty Speedway"),
    Route("Cheep Cheep Falls", "Salty Salty Speedway"),
    Route("Koopa Troopa Beach", "Dino Dino Jungle"),
    Route("Faraway Oasis", "Dino Dino Jungle"),
    Route("Peach Beach", "Dino Dino Jungle"),
    Route("Salty Salty Speedway", "Dino Dino Jungle"),
    Route("Great ? Block Ruins", "Dino Dino Jungle"),
    Route("Faraway Oasis", "Great ? Block Ruins"),
    Route("Peach Beach", "Great ? Block Ruins"),
    Route("Salty Salty Speedway", "Great ? Block Ruins"),
    Route("Dino Dino Jungle", "Great ? Block Ruins"),
    Route("DK Pass", "Cheep Cheep Falls"),
    Route("Starview Peak", "Cheep Cheep Falls"),
    Route("Sky-High Sundae", "Cheep Cheep Falls"),
    Route("Wario Shipyard", "Cheep Cheep Falls"),
    Route("Faraway Oasis", "Cheep Cheep Falls"),
    Route("Peach Stadium", "Cheep Cheep Falls"),
    Route("Salty Salty Speedway", "Cheep Cheep Falls"),
    Route("Dandelion Depths", "Cheep Cheep Falls"),
    Route("Moo Moo Meadows", "Cheep Cheep Falls"),
    Route("Choco Mountain", "Cheep Cheep Falls"),
    Route("Mario Circuit", "Dandelion Depths"),
    Route("DK Pass", "Dandelion Depths"),
    Route("Starview Peak", "Dandelion Depths"),
    Route("Sky-High Sundae", "Dandelion Depths"),
    Route("Cheep Cheep Falls", "Dandelion Depths"),
    Route("Boo Cinema", "Dandelion Depths"),
    Route("Moo Moo Meadows", "Dandelion Depths"),
    Route("Toad's Factory", "Dandelion Depths"),
    Route("Acorn Heights", "Dandelion Depths"),
    Route("Acorn Heights", "Boo Cinema"),
    Route("Dry Bones Burnout", "Boo Cinema"),
    Route("Starview Peak", "Boo Cinema"),
    Route("Dandelion Depths", "Boo Cinema"),
    Route("Mario Circuit", "Boo Cinema"),
    Route("Wario Stadium", "Dry Bones Burnout"),
    Route("Airship Fortress", "Dry Bones Burnout"),
    Route("Boo Cinema", "Dry Bones Burnout"),
    Route("Moo Moo Meadows", "Dry Bones Burnout"),
    Route("Toad's Factory", "Dry Bones Burnout"),
    Route("Bowser's Castle", "Dry Bones Burnout"),
    Route("Acorn Heights", "Dry Bones Burnout"),
    Route("Mario Circuit", "Dry Bones Burnout"),
    Route("Crown City", "Moo Moo Meadows"),
    Route("DK Pass", "Moo Moo Meadows"),
    Route("Peach Stadium", "Moo Moo Meadows"),
    Route("Cheep Cheep Falls", "Moo Moo Meadows"),
    Route("Dandelion Depths", "Moo Moo Meadows"),
    Route("Dry Bones Burnout", "Moo Moo Meadows"),
    Route("Choco Mountain", "Moo Moo Meadows"),
    Route("Toad's Factory", "Moo Moo Meadows"),
    Route("Mario Circuit", "Moo Moo Meadows"),
    Route("Mario Bros. Circuit", "Choco Mountain"),
    Route("Crown City", "Choco Mountain"),
    Route("Whistlestop Summit", "Choco Mountain"),
    Route("Shy Guy Bazaar", "Choco Mountain"),
    Route("Wario Stadium", "Choco Mountain"),
    Route("Peach Stadium", "Choco Mountain"),
    Route("Cheep Cheep Falls", "Choco Mountain"),
    Route("Moo Moo Meadows", "Choco Mountain"),
    Route("Toad's Factory", "Choco Mountain"),
    Route("Bowser's Castle", "Choco Mountain"),
    Route("Mario Bros. Circuit", "Toad's Factory"),
    Route("Wario Stadium", "Toad's Factory"),
    Route("Airship Fortress", "Toad's Factory"),
    Route("Peach Stadium", "Toad's Factory"),
    Route("Dandelion Depths", "Toad's Factory"),
    Route("Dry Bones Burnout", "Toad's Factory"),
    Route("Moo Moo Meadows", "Toad's Factory"),
    Route("Choco Mountain", "Toad's Factory"),
    Route("Bowser's Castle", "Toad's Factory"),
    Route("Acorn Heights", "Toad's Factory"),
    Route("Mario Circuit", "Toad's Factory"),
    Route("Wario Stadium", "Bowser's Castle"),
    Route("Airship Fortress", "Bowser's Castle"),
    Route("Dry Bones Burnout", "Bowser's Castle"),
    Route("Choco Mountain", "Bowser's Castle"),
    Route("Toad's Factory", "Bowser's Castle"),
    Route("Mario Circuit", "Bowser's Castle"),
    Route("Dandelion Depths", "Acorn Heights"),
    Route("Boo Cinema", "Acorn Heights"),
    Route("Dry Bones Burnout", "Acorn Heights"),
    Route("Toad's Factory", "Acorn Heights"),
    Route("Mario Circuit", "Acorn Heights"),
    Route("Starview Peak", "Mario Circuit"),
    Route("Dandelion Depths", "Mario Circuit"),
    Route("Boo Cinema", "Mario Circuit"),
    Route("Dry Bones Burnout", "Mario Circuit"),
    Route("Moo Moo Meadows", "Mario Circuit"),
    Route("Toad's Factory", "Mario Circuit"),
    Route("Bowser's Castle", "Mario Circuit"),
    Route("Acorn Heights", "Mario Circuit"),
    Route("Peach Stadium", "Rainbow Road"),
]
